version: "2"
services:
  redis:
    image: redis:latest
    container_name: "redis-dock"
    user: "redis"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      -  scrumblr-net
  node:
    image: "scrumblr:latest"
    container_name: "scrumblr"
    user: "node"
    ports:
      - "1000:1000"
    networks:
      - scrumblr-net
networks:
    scrumblr-net:
      driver: bridge
      name: scrumblr-net